{% set version = "0.1.4" %}
{% set sha256 = "abb3c8da13e4be639fd1b9355e48355fb87e75c1e1fa23df71ed5b6e83ec372a" %}

package:
  name: p2m2tools
  version: '{{ version }}'

source:
  url: https://github.com/p2m2/p2m2tools/releases/download/{{ version }}/p2m2tools.jar
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0

requirements:
  run:
    - openjdk >=8

test:
  commands:
    - "bash -c 'java -cp jar/p2m2tools.jar fr.inrae.metabolomics.p2m2.OpenLabCDS2CsvCommand --help 2>&1 | grep Usage'"

about:
  home: https://www6.inrae.fr/p2m2
  license: MIT
  license_family: MIT
  summary: Java tools for working with NGS data in the BAM format
  description: >- 
    Development of it and bioinformatics tools for the activities of the P2M2 platform. 
    All the tools developed are accessible via the Galaxy instance of the Genouest platform (https://galaxy.genouest.org/) 
  dev_url: https://github.com/p2m2/p2m2tools

